### ISSUE TITLE
nmr_read_samples_dir

### ISSUE THREAD

**Issue by lucanico** [sipss/AlpsNMR#52] opened 2021-08-03 04:45 UTC
I am experiencing an issue with the function nmr_read_samples_dir.
 I wan to read a set of NMR experiments that are organised as folllows;
maindir ->Sample "x"->pdata-> 1-> 1r

when I use  nmr_read_samples_dir function I've got the following error:

Warning message in value[[3L]](cond):
"Error loading sample: \NMR_workflow_LN\awri_spe_samples\Sample 2"
'FUN.VALUE' must be a vector

This message is repeated for each sample of the dataset.

These experiments were acquired on a 900 MHz Nmr.

I am wondering where I'm going wrong.

Thanks for your attention.

**Comment by zeehio** [comment] 2021-08-03 18:52
Thanks for reporting the issue 

I believe this issue is already fixed on the master branch.

Could you try to install the latest development version?

```r
install.packages("remotes")
remotes::install_github("sipss/AlpsNMR")
```

And try again to check if the issue is fixed?

If you confirm that the issue is fixed I'll ask the release manager to make a new upload to Bioconductor with minor fixes.

**Comment by lucanico** [comment] 2021-08-03 22:13
Thank you very much. I'll install from GitHub and let you know if this is still happening.
Kind regards,
Luca

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by lucanico** [comment] 2021-08-04 05:10
I have reinstalled and tested and it is working now.
Thank you for your assistance, much appreciated.

Regards,
Luca

**Closed** 2021-08-04 20:18 UTC
